programs=[
"BS Agribusiness Management",
"BS Development Communication",
"BA English and Language Studies",
"BA History",
"BA Political Science",
"BA Sociology",
"BS Biology",
"BS Chemistry",
"BS Mathematics",
"BS Physics",
"BS Psychology",
"BS Accountancy",
"BS Accounting Information System",
"BS Internal Auditing",
"BS Management Accounting",
"BS Business Administration",
"BS Office Administration",
"BS Hospitality Management",
"BS Tourism Management",
"BS Entrepreneurship",
"BS Business Analytics and Operations Management",
"BS Agricultural and Biosystems Engineering",
"BS Civil Engineering",
"BS Electrical Engineering",
"BS Information Technology",
"BS Mechanical Engineering",
"BS Home Economics",
"BS Food Technology",
"BS Nutrition and Dietetics",
"BS Hospitality Management",
"BS Environmental Science",
"BS Forestry",
"BS Nursing"]